### ISSUE TITLE
Apr 17's update doesn't supported

### ISSUE THREAD

**Issue by asturel** [nuadi/gta5checkscript#1]

**Comment by nuadi** [comment]
Which files are not supported?

**Comment by asturel** [comment]
Unknown file: Grand Theft Auto V\update\update.rpf
Unknown file: Grand Theft Auto V\update\x64\metadata.dat

**Comment by nuadi** [comment]
Ah, ok. Yes, I'm aware of those two files. The launcher appears to ignore them when you remove them, so they might be temporary files. I'd ignore them for now. I am working to confirm if they are temporary or not.

**Comment by nuadi** [comment]
I finally have a completely valid installation.

These two files are now included in the script.

* The `metadata.dat` file is now included in `hashes.txt`.
* The `update.rpf` file is now included inside the ignore list. This file is required to launch the game, but the launcher will not repair it if you simply rename the file. Further testing will be required to verify the hash of this file, so for now I've placed it into the ignore list.
