### ISSUE TITLE
Unknown files

### ISSUE THREAD

**Issue by harrisonlingren** [nuadi/gta5checkscript#2]
`UNKNOWN FILE: Grand Theft Auto V\installscript.vdf`
`UNKNOWN FILE: Grand Theft Auto V\steam_api64.dll`
`UNKNOWN FILE: Grand Theft AutoV\Installers\Social Club v1.1.5.8 Setup.exe`

I'm using the steam version, obviously.

**Comment by joelabeyta** [comment]
I have the same three files coming up as unknown.

**Comment by nuadi** [comment]
Thanks for reporting this. Added in logic to ignore these files.
